# Generated by Django 4.2.7 on 2024-02-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verificator',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, default='39871328', max_length=8, null=True, verbose_name='код подтверждения почты'),
        ),
    ]
