# Generated by Django 4.2.7 on 2024-02-06 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='next_try',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='следующая попытка'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='send_finish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='send_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала рассылки'),
        ),
    ]
