# Generated by Django 4.2.7 on 2024-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_sending_next_try_alter_sending_send_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='server_answer',
            field=models.BooleanField(default=False, verbose_name='ответ сервера'),
        ),
    ]
