# Generated by Django 4.2.7 on 2024-02-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_sending_next_try_alter_sending_send_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ('send_start',), 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
