# Generated by Django 4.2.7 on 2024-02-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_logs_server_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'ordering': ('send_start',), 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
