# Generated by Django 4.2.7 on 2024-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_sending_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='server_answer',
            field=models.TextField(blank=True, default='', null=True, verbose_name='ответ сервера'),
        ),
    ]
